/* Đức Anh Maintenance — Building Module V1.0
   App Shell module.
   UI/behavior is based on the locked Customer Module pattern and the current buildings_V1.25_FIXED.html.
   No Firebase schema changes. No unrelated module changes.
*/
import {
  createBuilding,
  getBuildings,
  getElevators,
  getCustomers
} from "../core/firestore-v1.js";

const BUILDING_CSS = `
.building-module{padding:28px 0 40px}
.building-module .building-container{width:min(1500px,100%);margin:0 auto}
.building-module .building-header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin-bottom:26px}
.building-module .building-eyebrow{margin:0 0 7px;color:#f5c400;font-size:11px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}
.building-module .building-title{margin:0;font-size:clamp(28px,3vw,38px);line-height:1.1;letter-spacing:-.03em}
.building-module .building-subtitle{margin:9px 0 0;color:#969696;font-size:14px}
.building-module .primary-button{display:inline-flex;align-items:center;justify-content:center;gap:9px;border:0;border-radius:9px;padding:12px 17px;background:#f5c400;color:#080808;font-weight:800}
.building-module .primary-button:hover{background:#ffd83d}
.building-module .primary-button:disabled{opacity:.6;cursor:not-allowed}
.building-module .building-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}
.building-module .kpi-card{position:relative;overflow:hidden;min-height:112px;padding:18px;border:1px solid #292929;border-radius:12px;background:linear-gradient(145deg,#151515,#101010)}
.building-module .kpi-label{color:#969696;font-size:12px}.building-module .kpi-value{margin-top:9px;font-size:29px;font-weight:800}.building-module .kpi-note{margin-top:5px;color:#969696;font-size:11px}
.building-module .building-toolbar{display:flex;align-items:center;gap:10px;margin-bottom:14px;padding:13px;border:1px solid #292929;border-radius:12px;background:#121212}
.building-module .search-box{position:relative;flex:1;min-width:180px}.building-module .search-box span{position:absolute;left:13px;top:50%;transform:translateY(-50%);color:#777}
.building-module .search-box input,.building-module .filter-select{width:100%;height:42px;border:1px solid #292929;border-radius:8px;outline:none;background:#0d0d0d;color:#f4f4f4}
.building-module .search-box input{padding:0 13px 0 37px}.building-module .filter-select{width:190px;padding:0 12px}
.building-module .search-box input:focus,.building-module .filter-select:focus{border-color:#f5c400}
.building-module .building-table-card{overflow:hidden;border:1px solid #292929;border-radius:12px;background:#121212}
.building-module .table-header{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid #292929}
.building-module .table-title{font-size:14px;font-weight:800}.building-module .table-count{color:#969696;font-size:12px}
.building-module .firebase-message{margin:0;padding:11px 16px;border-bottom:1px solid #292929;color:#aaa;font-size:12px;line-height:1.5;display:none}
.building-module .firebase-message.show{display:block}.building-module .firebase-message.success{color:#38c793;background:rgba(56,199,147,.04)}.building-module .firebase-message.error{color:#ef6262;background:rgba(239,98,98,.04)}.building-module .firebase-message.info{color:#aaa;background:rgba(255,255,255,.02)}
.building-module .table-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}.building-module table{width:100%;min-width:980px;border-collapse:collapse}
.building-module th{padding:13px 16px;border-bottom:1px solid #292929;color:#858585;font-size:10px;font-weight:700;letter-spacing:.08em;text-align:left;white-space:nowrap;text-transform:uppercase}
.building-module td{padding:15px 16px;border-bottom:1px solid #202020;color:#ddd;font-size:13px;vertical-align:middle}
.building-module tbody tr:hover{background:#171717}.building-module tbody tr:last-child td{border-bottom:0}
.building-module th:last-child,.building-module td:last-child{position:sticky;right:0;background:#121212;box-shadow:-10px 0 18px rgba(0,0,0,.32);z-index:1;min-width:82px}.building-module thead th:last-child{z-index:3}.building-module tbody tr:hover td:last-child{background:#171717}
.building-module .building-name{color:#fff;font-weight:700}.building-module .building-id{margin-top:4px;color:#666;font-size:10px;font-family:monospace}.building-module .muted{color:#969696}
.building-module .status{display:inline-flex;align-items:center;gap:6px;padding:5px 9px;border-radius:999px;font-size:10px;font-weight:700;white-space:nowrap}.building-module .status:before{content:"";width:6px;height:6px;border-radius:50%}
.building-module .status.active{background:rgba(56,199,147,.1);color:#38c793}.building-module .status.active:before{background:#38c793}
.building-module .status.care{background:rgba(245,196,0,.1);color:#f5c400}.building-module .status.care:before{background:#f5c400}
.building-module .status.inactive{background:rgba(239,98,98,.1);color:#ef6262}.building-module .status.inactive:before{background:#ef6262}
.building-module .action-button,.building-module .icon-button{border:1px solid #292929;border-radius:7px;padding:7px 10px;background:#101010;color:#ccc;font-size:11px}.building-module .action-button:hover{border-color:#f5c400;color:#f5c400}
.building-module .table-footer{display:flex;align-items:center;justify-content:space-between;padding:13px 18px;border-top:1px solid #292929;color:#969696;font-size:11px}
.building-module .mobile-building-list{display:none}.building-module .building-card{padding:15px;border-bottom:1px solid #202020}.building-module .building-card-top{display:flex;justify-content:space-between;gap:10px}.building-module .building-card-contact{margin:9px 0;color:#bbb;font-size:12px;line-height:1.55}
.building-module .building-card-stats{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:10px}.building-module .mini-stat{padding:9px;border:1px solid #292929;border-radius:8px;background:#0d0d0d}.building-module .mini-stat b{display:block;font-size:15px}.building-module .mini-stat span{color:#777;font-size:9px}.building-module .building-card-bottom{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:12px}
.building-module .bm-backdrop{position:fixed;inset:0;z-index:3000;display:none;background:rgba(0,0,0,.78);backdrop-filter:blur(5px);-webkit-backdrop-filter:blur(5px)}
.building-module .bm-backdrop.show{display:flex}.building-module .bm-drawer{position:absolute;top:0;right:0;width:min(620px,100%);height:100%;overflow-y:auto;background:#111;border-left:1px solid #292929;box-shadow:-25px 0 80px rgba(0,0,0,.55)}
.building-module .bm-head{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;gap:12px;padding:20px;border-bottom:1px solid #292929;background:rgba(17,17,17,.96);backdrop-filter:blur(10px)}
.building-module .bm-head h2{margin:0;font-size:20px}.building-module .bm-kicker,.building-module .form-section-title,.building-module .detail-section-title{margin:0 0 7px;color:#f5c400;font-size:10px;letter-spacing:.12em;text-transform:uppercase}
.building-module .building-id{margin-top:4px;color:#666;font-size:10px;font-family:monospace}.building-module .bm-body{padding:20px}
.building-module .detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:24px}.building-module .detail-item{padding:12px;border:1px solid #292929;border-radius:9px;background:#151515}.building-module .detail-item span{display:block;color:#777;font-size:10px;margin-bottom:5px}.building-module .detail-item b{font-size:13px}
.building-module .detail-tabs{display:flex;gap:7px;overflow-x:auto;padding-bottom:3px;margin-bottom:18px}.building-module .detail-tab{flex:0 0 auto;border:1px solid #292929;border-radius:8px;padding:9px 11px;background:#151515;color:#aaa;font-size:11px}.building-module .detail-tab.active{border-color:#f5c400;background:rgba(245,196,0,.09);color:#f5c400}
.building-module .detail-list{display:grid;gap:8px}.building-module .detail-row{display:flex;justify-content:space-between;gap:10px;padding:11px 12px;border:1px solid #292929;border-radius:8px;background:#0d0d0d;font-size:12px}.building-module .detail-row span{color:#999}.building-module .empty{padding:16px;border:1px dashed #292929;border-radius:9px;color:#777;font-size:12px;text-align:center}
.building-module .location-profile{margin-bottom:24px}.building-module .location-profile-card{padding:12px;border:1px solid #292929;border-radius:10px;background:#0d0d0d}.building-module .location-profile-title{color:#eee;font-size:12px;font-weight:700}.building-module .location-profile-meta{margin-top:5px;color:#777;font-size:10px;line-height:1.5}.building-module .location-profile-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:11px}.building-module .location-profile-empty{padding:14px;border:1px dashed #292929;border-radius:10px;color:#777;font-size:11px}
.building-module .bm-modal{width:min(720px,100%);height:min(800px,calc(100dvh - 40px));max-height:calc(100dvh - 40px);display:flex;flex-direction:column;overflow:hidden;border:1px solid #292929;border-radius:14px;background:#111;box-shadow:0 25px 80px rgba(0,0,0,.55)}
.building-module .bm-modal-head{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;align-items:center;padding:17px 20px;border-bottom:1px solid #292929;background:#111}.building-module .bm-modal-head h2{margin:0;font-size:18px}
.building-module .close-button{width:38px;height:38px;border:1px solid #292929;border-radius:9px;background:#171717;color:#aaa;font-size:22px}.building-module .bm-modal>form{display:flex;flex:1;min-height:0;flex-direction:column;overflow:hidden}
.building-module .bm-modal-body{flex:1;min-height:0;overflow-y:auto;padding:20px;-webkit-overflow-scrolling:touch}.building-module .form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-bottom:24px}.building-module .form-field.full{grid-column:1/-1}.building-module .form-field label{display:block;margin-bottom:6px;color:#aaa;font-size:11px}
.building-module .form-field input,.building-module .form-field select,.building-module .form-field textarea{width:100%;min-height:46px;border:1px solid #292929;border-radius:9px;outline:none;background:#0b0b0b;color:#eee;padding:11px 12px;font-size:16px}.building-module .form-field input:focus,.building-module .form-field select:focus,.building-module .form-field textarea:focus{border-color:#f5c400}.building-module .form-field textarea{min-height:95px;resize:vertical}.building-module .form-help{margin-top:6px;color:#666;font-size:10px;line-height:1.4}
.building-module .bm-modal-foot{display:flex;justify-content:flex-end;gap:9px;padding:13px 20px;border-top:1px solid #292929;background:#111}.building-module .secondary-button{border:1px solid #292929;border-radius:8px;padding:11px 15px;background:#171717;color:#ccc}.building-module .secondary-button:hover{border-color:#555}
.building-module .location-box{padding:12px;border:1px solid #292929;border-radius:10px;background:#0d0d0d}.building-module .location-status{display:flex;align-items:flex-start;gap:10px}.building-module .location-dot{width:9px;height:9px;margin-top:5px;flex:0 0 auto;border-radius:50%;background:#666;box-shadow:0 0 0 4px rgba(255,255,255,.03)}.building-module .location-status.ready .location-dot{background:#f5c400;box-shadow:0 0 0 4px rgba(245,196,0,.1)}.building-module .location-status b{display:block;color:#eee;font-size:12px}.building-module .location-status small{display:block;margin-top:4px;color:#777;font-size:10px;line-height:1.4}
.building-module .location-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.building-module .location-button{min-height:40px;border:1px solid #292929;border-radius:8px;background:#151515;color:#ddd;font-size:11px;font-weight:700}.building-module .location-button:hover{border-color:#f5c400;color:#f5c400}.building-module .location-button.secondary-location{background:#111}.building-module .location-coordinates{display:none;margin-top:10px;padding-top:10px;border-top:1px solid #292929;color:#999;font-size:10px;line-height:1.5}.building-module .location-coordinates.show{display:block}
.building-module .loading-row{padding:30px 18px;color:#777;text-align:center;font-size:12px}
@media(max-width:900px){.building-module .building-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:640px){
 .building-module{padding:16px 0 30px}.building-module .building-header{flex-direction:column}.building-module .primary-button{width:100%;min-height:54px}.building-module .building-toolbar{flex-direction:column;align-items:stretch}.building-module .filter-select{width:100%}
 .building-module .table-scroll{display:none}.building-module .mobile-building-list{display:block}.building-module .table-footer{flex-direction:column;align-items:flex-start;gap:5px}
 .building-module .bm-drawer{width:100%;border-left:0}.building-module .detail-grid{grid-template-columns:1fr 1fr}
 .building-module .bm-backdrop.modal-backdrop{align-items:flex-start;justify-content:center;padding:0;overflow-y:auto}
 .building-module .bm-modal{width:100%;min-height:100dvh;height:auto;max-height:none;display:block;overflow:visible;border-radius:0;border:0}
 .building-module .bm-modal>form{display:block;min-height:auto;overflow:visible}.building-module .bm-modal-head{padding:calc(14px + env(safe-area-inset-top)) 16px 14px}.building-module .bm-modal-body{overflow:visible;padding:18px 16px 30px}.building-module .form-grid{grid-template-columns:1fr;gap:15px}.building-module .form-field.full{grid-column:auto}
 .building-module .form-field label{font-size:13px}.building-module .form-field input,.building-module .form-field select,.building-module .form-field textarea{min-height:50px;padding:13px 14px}.building-module .bm-modal-foot{padding:12px 16px calc(12px + env(safe-area-inset-bottom));position:relative}.building-module .bm-modal-foot .primary-button{flex:1;min-height:48px}.building-module .bm-modal-foot .secondary-button{min-width:84px}
}
`;

function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function statusLabel(s){const m={active:["Đang hoạt động","active"],care:["Cần chăm sóc","care"],inactive:["Ngừng hoạt động","inactive"]};const [l,c]=m[s]||["Chưa xác định","inactive"];return `<span class="status ${c}">${l}</span>`}
function typeLabel(t){return ({apartment:"Chung cư",office:"Văn phòng",factory:"Nhà máy",hotel:"Khách sạn",house:"Nhà riêng",hospital:"Bệnh viện",other:"Khác"})[t]||t||"Khác"}
function addressText(a){if(!a)return "—";if(typeof a==="string")return a||"—";return [a.detail,a.district,a.province].filter(Boolean).join(", ")||"—"}
function normalizeLocation(location){if(!location)return null;const lat=Number(location.lat),lng=Number(location.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return null;return {lat,lng,accuracy:Number.isFinite(Number(location.accuracy))?Number(location.accuracy):null,source:location.source||"map"}}
function managerName(b){if(b?.manager?.name)return b.manager.name;if(typeof b?.manager==="string")return b.manager;return "Chưa phân công"}
function formatCoordinates(location){const x=normalizeLocation(location);if(!x)return "";const a=x.accuracy?` · ±${Math.round(x.accuracy)} m`:"";return `${x.lat.toFixed(6)}, ${x.lng.toFixed(6)}${a}`}
function mapsUrl(location){const x=normalizeLocation(location);return x?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${x.lat},${x.lng}`)}`:"#"}

export async function mountBuildingModule(root){
  if(!root)throw new Error("BUILDING_ROOT_NOT_FOUND");
  if(!document.getElementById("building-module-style")){const style=document.createElement("style");style.id="building-module-style";style.textContent=BUILDING_CSS;document.head.appendChild(style)}

  root.innerHTML=`
  <section class="building-module">
    <div class="building-container">
      <header class="building-header">
        <div><p class="building-eyebrow">BUILDING MANAGEMENT</p><h1 class="building-title">Tòa nhà</h1><p class="building-subtitle">Quản lý tòa nhà, khách hàng, thang máy và trạng thái dịch vụ.</p></div>
        <button class="primary-button" id="bmAdd">＋ <span>Thêm tòa nhà</span></button>
      </header>
      <section class="building-kpis">
        <article class="kpi-card"><div class="kpi-label">Tổng tòa nhà</div><div class="kpi-value" id="bmKpiTotal">0</div><div class="kpi-note">Trong hệ thống</div></article>
        <article class="kpi-card"><div class="kpi-label">Đang hoạt động</div><div class="kpi-value" id="bmKpiActive">0</div><div class="kpi-note">Có dịch vụ đang theo dõi</div></article>
        <article class="kpi-card"><div class="kpi-label">Tổng thang máy</div><div class="kpi-value" id="bmKpiElevators">0</div><div class="kpi-note">Thuộc các tòa nhà</div></article>
        <article class="kpi-card"><div class="kpi-label">Cần chăm sóc</div><div class="kpi-value" id="bmKpiCare">0</div><div class="kpi-note">Cần xử lý / liên hệ</div></article>
      </section>
      <section class="building-toolbar">
        <div class="search-box"><span>⌕</span><input id="bmSearch" type="search" placeholder="Tìm tên tòa nhà, khách hàng, địa chỉ..." autocomplete="off"></div>
        <select class="filter-select" id="bmStatus"><option value="all">Tất cả trạng thái</option><option value="active">Đang hoạt động</option><option value="care">Cần chăm sóc</option><option value="inactive">Ngừng hoạt động</option></select>
      </section>
      <section class="building-table-card">
        <div class="table-header"><div class="table-title">Danh sách tòa nhà</div><div class="table-count" id="bmCount">Đang tải...</div></div>
        <div id="bmMessage" class="firebase-message"></div>
        <div class="table-scroll"><table><thead><tr><th>Tòa nhà</th><th>Khách hàng</th><th>Địa chỉ</th><th>Thang máy</th><th>Phụ trách</th><th>Trạng thái</th><th></th></tr></thead><tbody id="bmBody"></tbody></table></div>
        <div class="mobile-building-list" id="bmMobile"></div>
        <div class="table-footer"><span>Dữ liệu Firebase DEV — Firestore.</span><span>BUILDING MODULE V1.0</span></div>
      </section>
    </div>

    <div class="bm-backdrop" id="bmDetail"><aside class="bm-drawer"><div class="bm-head"><div><p class="bm-kicker">BUILDING PROFILE</p><h2 id="bmDetailName">—</h2><div class="building-id" id="bmDetailId">—</div></div><button class="close-button" id="bmCloseDetail">×</button></div><div class="bm-body"><div id="bmDetailStatus" style="margin-bottom:18px"></div><p class="detail-section-title">Thông tin tòa nhà</p><div class="detail-grid"><div class="detail-item"><span>Khách hàng</span><b id="bmCustomer">—</b></div><div class="detail-item"><span>Địa chỉ</span><b id="bmAddress">—</b></div><div class="detail-item"><span>Người phụ trách</span><b id="bmManager">—</b></div><div class="detail-item"><span>Loại công trình</span><b id="bmType">—</b></div></div><p class="detail-section-title">Vị trí công trình</p><div class="location-profile" id="bmLocation"><div class="location-profile-empty">Chưa có vị trí được ghim.</div></div><p class="detail-section-title">Tài sản & dịch vụ</p><div class="detail-grid"><div class="detail-item"><span>Thang máy</span><b id="bmElevators">0</b></div><div class="detail-item"><span>Hợp đồng</span><b>—</b></div><div class="detail-item"><span>Bảo trì</span><b>Đang theo dõi</b></div><div class="detail-item"><span>Work Order</span><b>—</b></div></div><div class="detail-tabs"><button class="detail-tab active" data-tab="elevators">Thang máy</button><button class="detail-tab" data-tab="contracts">Hợp đồng</button><button class="detail-tab" data-tab="maintenance">Bảo trì</button><button class="detail-tab" data-tab="workorders">Work Order</button></div><div class="detail-list" id="bmDetailList"></div></div></aside></div>

    <div class="bm-backdrop modal-backdrop" id="bmModal"><section class="bm-modal"><div class="bm-modal-head"><h2>Thêm tòa nhà</h2><button class="close-button" id="bmCloseModal">×</button></div><form id="bmForm"><div class="bm-modal-body"><p class="form-section-title">Thông tin tòa nhà</p><div class="form-grid"><div class="form-field full"><label>Tên tòa nhà *</label><input id="bmName" required placeholder="Nhập tên tòa nhà"></div><div class="form-field"><label>Khách hàng *</label><select id="bmCustomer" required><option value="">Đang tải khách hàng...</option></select><div class="form-help">Khách hàng được lấy trực tiếp từ Firebase DEV.</div></div><div class="form-field"><label>Loại công trình</label><select id="bmType"><option value="apartment">Chung cư</option><option value="office">Văn phòng</option><option value="factory">Nhà máy</option><option value="hotel">Khách sạn</option><option value="house">Nhà riêng</option><option value="hospital">Bệnh viện</option><option value="other">Khác</option></select></div><div class="form-field full"><label>Địa chỉ</label><input id="bmAddress" placeholder="Địa chỉ tòa nhà"></div><div class="form-field"><label>Tỉnh / Thành phố</label><input id="bmProvince" placeholder="Ví dụ: Hải Phòng"></div><div class="form-field"><label>Quận / Huyện</label><input id="bmDistrict" placeholder="Ví dụ: Lê Chân"></div><div class="form-field full"><label>📍 Vị trí công trình</label><div class="location-box"><div class="location-status" id="bmLocationStatus"><span class="location-dot"></span><div><b>Chưa ghim vị trí</b><small>Hãy lấy GPS hiện tại hoặc chọn trên bản đồ.</small></div></div><div class="location-actions"><button class="location-button" id="bmUseGps" type="button">📍 Lấy vị trí hiện tại</button><button class="location-button secondary-location" id="bmChooseMap" type="button">🗺 Chọn trên bản đồ</button></div><div class="location-coordinates" id="bmLocationCoordinates"></div></div></div><div class="form-field"><label>Người phụ trách</label><input id="bmManager" placeholder="Nhân sự phụ trách"></div><div class="form-field"><label>Số điện thoại liên hệ</label><input id="bmPhone" placeholder="Số điện thoại"></div><div class="form-field full"><label>Ghi chú</label><textarea id="bmNote" placeholder="Thông tin bổ sung..."></textarea></div></div></div><div class="bm-modal-foot"><button class="secondary-button" id="bmCancel" type="button">Hủy</button><button class="primary-button" type="submit">Lưu tòa nhà</button></div></form></section></div>
  </section>`;

  let customers=[],buildings=[],elevators=[],selected=null,selectedLocation=null;
  const q=s=>root.querySelector(s);
  const customerName=id=>customers.find(x=>x.id===id)?.name||"Chưa xác định";
  const elevatorsFor=id=>elevators.filter(x=>x.buildingId===id);
  const showMsg=(t,type="")=>{const e=q("#bmMessage");e.textContent=t||"";e.className="firebase-message"+(t?" show":"")+(type?` ${type}`:"")};

  function updateKpi(){q("#bmKpiTotal").textContent=buildings.length;q("#bmKpiActive").textContent=buildings.filter(x=>x.status==="active").length;q("#bmKpiElevators").textContent=elevators.length;q("#bmKpiCare").textContent=buildings.filter(x=>x.status==="care").length}
  function renderCustomerOptions(){const e=q("#bmCustomer");e.innerHTML=customers.length?`<option value="">Chọn khách hàng</option>${customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join("")}`:`<option value="">Chưa có khách hàng</option>`}
  function filtered(){const text=q("#bmSearch").value.trim().toLowerCase(),status=q("#bmStatus").value;return buildings.filter(b=>{const hay=[b.name,customerName(b.customerId),addressText(b.address),managerName(b)].join(" ").toLowerCase();return (!text||hay.includes(text))&&(status==="all"||b.status===status)})}
  function render(){updateKpi();const list=filtered();q("#bmCount").textContent=`${list.length} tòa nhà`;q("#bmBody").innerHTML=list.length?list.map(b=>{const es=elevatorsFor(b.id);return `<tr><td><div class="building-name">${esc(b.name)}</div><div class="building-id">${esc(b.id)}</div></td><td>${esc(customerName(b.customerId))}</td><td>${esc(addressText(b.address))}</td><td>${es.length}</td><td>${esc(managerName(b))}</td><td>${statusLabel(b.status)}</td><td><button class="action-button" data-view="${esc(b.id)}" type="button">Xem</button></td></tr>`}).join(""):`<tr><td colspan="7"><div class="loading-row">Chưa có tòa nhà trong Firebase.</div></td></tr>`;q("#bmMobile").innerHTML=list.map(b=>{const es=elevatorsFor(b.id);return `<article class="building-card"><div class="building-card-top"><div><div class="building-name">${esc(b.name)}</div><div class="building-id">${esc(b.id)}</div></div>${statusLabel(b.status)}</div><div class="building-card-contact">${esc(customerName(b.customerId))}<br>${esc(addressText(b.address))}<br>Phụ trách: ${esc(managerName(b))}</div><div class="building-card-stats"><div class="mini-stat"><b>${es.length}</b><span>THANG MÁY</span></div><div class="mini-stat"><b>—</b><span>HỢP ĐỒNG</span></div><div class="mini-stat"><b>—</b><span>WORK ORDER</span></div></div><div class="building-card-bottom"><span class="muted">${esc(typeLabel(b.type))}</span><button class="action-button" data-view="${esc(b.id)}" type="button">Xem hồ sơ</button></div></article>`}).join("")}

  function updateLocationUI(){const s=q("#bmLocationStatus"),c=q("#bmLocationCoordinates");if(!s||!c)return;const x=normalizeLocation(selectedLocation);if(!x){s.classList.remove("ready");s.innerHTML=`<span class="location-dot"></span><div><b>Chưa ghim vị trí</b><small>Hãy lấy GPS hiện tại hoặc chọn trên bản đồ.</small></div>`;c.className="location-coordinates";c.textContent="";return}s.classList.add("ready");s.innerHTML=`<span class="location-dot"></span><div><b>Đã ghim vị trí</b><small>Nguồn: ${x.source==="gps"?"GPS thiết bị":"Chọn trên bản đồ"}</small></div>`;c.className="location-coordinates show";c.textContent=formatCoordinates(x)}
  function resetLocation(){selectedLocation=null;updateLocationUI()}
  function requestGps(){if(!navigator.geolocation){showMsg("Thiết bị/trình duyệt không hỗ trợ GPS.","error");return}showMsg("Đang lấy vị trí hiện tại...","info");navigator.geolocation.getCurrentPosition(p=>{selectedLocation={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,source:"gps"};updateLocationUI();showMsg("Đã lấy vị trí hiện tại.","success")},e=>{console.error(e);const m={1:"Bạn chưa cấp quyền vị trí cho trình duyệt.",2:"Không xác định được vị trí hiện tại.",3:"Lấy vị trí quá lâu. Vui lòng thử lại."};showMsg(m[e.code]||"Không thể lấy vị trí hiện tại.","error")},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
  function chooseMap(){showMsg("Bản đồ chọn điểm thủ công sẽ được hoàn thiện ở bước Map UI. Hiện tại hãy dùng 'Lấy vị trí hiện tại' để ghim GPS.","info")}
  function renderLocation(location){const e=q("#bmLocation"),x=normalizeLocation(location);if(!x){e.innerHTML=`<div class="location-profile-empty">Chưa có vị trí được ghim.</div>`;return}const url=mapsUrl(x);e.innerHTML=`<div class="location-profile-card"><div class="location-profile-title">📍 ${esc(formatCoordinates(x))}</div><div class="location-profile-meta">Nguồn: ${x.source==="gps"?"GPS thiết bị":"Chọn trên bản đồ"}</div><div class="location-profile-actions"><a class="action-button" href="${esc(url)}" target="_blank" rel="noopener">Mở bản đồ</a><a class="action-button" href="${esc(url)}" target="_blank" rel="noopener">Chỉ đường</a></div></div>`}

  function detail(id){const b=buildings.find(x=>x.id===id);if(!b)return;selected=b;const es=elevatorsFor(b.id);q("#bmDetailName").textContent=b.name||"—";q("#bmDetailId").textContent=b.id||"—";q("#bmDetailStatus").innerHTML=statusLabel(b.status);q("#bmCustomer").textContent=customerName(b.customerId);q("#bmAddress").textContent=addressText(b.address);q("#bmManager").textContent=managerName(b);q("#bmType").textContent=typeLabel(b.type);q("#bmElevators").textContent=es.length;renderLocation(b.location);tab("elevators");q("#bmDetail").classList.add("show");document.body.style.overflow="hidden"}
  function tab(t){q("#bmDetail").querySelectorAll(".detail-tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));if(!selected)return;const es=elevatorsFor(selected.id);if(t==="elevators"){q("#bmDetailList").innerHTML=es.length?es.map(e=>{const m=e.technical?.machine?.brand||"—",c=e.technical?.controller?.brand||"—";return `<div class="detail-row"><div><b>${esc(e.name||"Thang máy")}</b><div class="building-id">${esc(e.id)}</div></div><span>${esc(m)} · ${esc(c)}</span></div>`}).join(""):`<div class="empty">Chưa có thang máy liên kết với tòa nhà này.</div>`;return}const p={contracts:["Hợp đồng","Chưa kết nối module Hợp đồng"],maintenance:["Bảo trì","Chưa kết nối module Bảo trì"],workorders:["Work Order","Chưa kết nối module Work Order"]}[t]||["Dữ liệu","Chưa có dữ liệu"];q("#bmDetailList").innerHTML=`<div class="detail-row"><b>${esc(p[0])}</b><span>${esc(p[1])}</span></div>`}

  async function load(){showMsg("Đang tải dữ liệu từ Firebase...","info");q("#bmBody").innerHTML=`<tr><td colspan="7"><div class="loading-row">Đang tải dữ liệu từ Firebase...</div></td></tr>`;try{[customers,buildings,elevators]=await Promise.all([getCustomers(),getBuildings(),getElevators()]);customers=customers||[];buildings=buildings||[];elevators=elevators||[];renderCustomerOptions();render();showMsg(`Đã kết nối Firestore. ${buildings.length} tòa nhà.`,'success')}catch(e){console.error(e);customers=[];buildings=[];elevators=[];renderCustomerOptions();render();showMsg(`Lỗi Firebase: ${e.message}`,'error')}}
  async function openModal(){try{const fresh=await getCustomers();customers=fresh||customers}catch(e){console.error("REFRESH CUSTOMER ERROR:",e)}renderCustomerOptions();resetLocation();q("#bmModal").classList.add("show");document.body.style.overflow="hidden";setTimeout(()=>q("#bmName")?.focus(),50)}
  function closeModal(){q("#bmModal").classList.remove("show");document.body.style.overflow="";q("#bmForm").reset();resetLocation()}
  function closeDetail(){q("#bmDetail").classList.remove("show");document.body.style.overflow="";selected=null}

  q("#bmAdd").onclick=openModal;q("#bmCloseModal").onclick=closeModal;q("#bmCancel").onclick=closeModal;q("#bmCloseDetail").onclick=closeDetail;q("#bmDetail").onclick=e=>{if(e.target.id==="bmDetail")closeDetail()};q("#bmModal").onclick=e=>{if(e.target.id==="bmModal")closeModal()};q("#bmSearch").oninput=render;q("#bmStatus").onchange=render;q("#bmUseGps").onclick=requestGps;q("#bmChooseMap").onclick=chooseMap;q("#bmForm").onsubmit=async e=>{e.preventDefault();const btn=q("#bmForm button[type=submit]"),old=btn.textContent;const name=q("#bmName").value.trim(),customerId=q("#bmCustomer").value;if(!name){showMsg("Vui lòng nhập tên tòa nhà.","error");return}if(!customerId){showMsg("Vui lòng chọn khách hàng.","error");return}btn.disabled=true;btn.textContent="Đang lưu...";try{const created=await createBuilding({name,customerId,type:q("#bmType").value||"other",address:{province:q("#bmProvince").value.trim(),district:q("#bmDistrict").value.trim(),detail:q("#bmAddress").value.trim()},location:normalizeLocation(selectedLocation),manager:{name:q("#bmManager").value.trim(),phone:q("#bmPhone").value.trim()},status:"active"});closeModal();await load();showMsg(`Đã tạo tòa nhà "${created.name}". Firebase Auto ID: ${created.id}`,"success")}catch(err){console.error(err);showMsg(`Không thể tạo tòa nhà: ${err?.message||"UNKNOWN_ERROR"}`,"error")}finally{btn.disabled=false;btn.textContent=old}};
  q("#bmBody");root.addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)detail(b.dataset.view);const t=e.target.closest(".detail-tab");if(t)tab(t.dataset.tab)});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeDetail();closeModal()}});
  await load();
}
